services:
  - type: web
    name: EncrCourse
    plan: pro
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/chutpagludotnet/downCourseEditEncr
    branch: main
    autoDeploy: false
    region: virginia  # Correct region value for Virginia
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      # - key: WEBHOOK
      #   sync: false
      - key: PORT
        value: 8000
